services:
  ldap:
    image: dcm4che/slapd-dcm4chee:2.6.7-33.1
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "389:389"
    environment:
      STORAGE_DIR: /storage/fs1
      LDAP_ROOTPASS: pacs
    volumes:
      - ldap_data:/var/lib/openldap/openldap-data
      - ldap_conf:/etc/openldap/slapd.d
    restart: always
  db:
    image: dcm4che/postgres-dcm4chee:17.1-33
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pacsdb
      POSTGRES_USER: pacs
      POSTGRES_PASSWORD: pacs
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - db_data:/var/lib/postgresql/data
    restart: always
  arc:
    image: dcm4che/dcm4chee-arc-psql:5.33.1
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
      - "9993:9993"
      - "11112:11112"
      - "2762:2762"
      - "2575:2575"
      - "12575:12575"
    environment:
      LDAP_URL: ldap://ldap:389
      LDAP_ROOTPASS: pacs
      POSTGRES_DB: pacsdb
      POSTGRES_USER: pacs
      POSTGRES_PASSWORD: pacs
      WILDFLY_CHOWN: /storage
      WILDFLY_WAIT_FOR: ldap:389 db:5432
    depends_on:
      - ldap
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - wildfly_data:/opt/wildfly/standalone
      - storage_data:/storage
    restart: always

volumes:
  ldap_data:
  ldap_conf:
  db_data:
  wildfly_data:
  storage_data:

#  Create and start the 3 containers:      docker-compose -p dcm4chee up -d
#    stop all 3 containers:       docker-compose -p dcm4chee stop
#  start all 3 containers:        docker-compose -p dcm4chee start
#  delete container:         docker-compose -p dcm4chee down